spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
      mode: always
logging:
  level:
    com.mybatisplus.mybatis_plus_sample_active_record : debug
    '[org.apache.ibatis]': debug
    '[org.mybatis.spring]': debug
    '[com.zaxxer.hikari]': debug
    p6spy: DEBUG
    root: INFO
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
# p6spy configuration to show SQL with parameter values
p6spy:
  config:
    logMessageFormat: com.p6spy.engine.logging.format.SingleLineFormat
    # optional: include stacktrace, timestamp, execution time:
    # append: true

       
     